### ISSUE TITLE
objective c integration

### ISSUE THREAD

**Issue by ramz3001** [FlickType/FlickTypeKit#1]
not able to integrate it with objective c code, any suggestion \?

**Comment by keleftheriou** [comment]
Hey, what is the exact error you are getting? Can you provide some more details?

**Comment by ramz3001** [comment]
actually , i added at the top of my implementation file @import FlickTypeKit;

but at the method :

[self presentTextInputControllerWithSuggestions:array allowedInputMode:WKTextInputModeAllowAnimatedEmoji completion:^(NSArray *array){

I am not able to add the flickTypeMode within the method , i get this error :
No visible @interface for 'TableViewRowController' declares the selector 'presentTextInputControllerWithSuggestions:allowedInputMode:flickTypeMode:completion:’



On Jun 6, 2019, at 11:34 PM, Kosta Eleftheriou <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, what is the exact error you are getting? Can you provide some more details?

**Comment by keleftheriou** [comment]
You can only call `presentTextInputControllerWithSuggestions` on a `WKInterfaceController`. 

Is your `TableViewRowController` a subclass of `WKInterfaceController`? 

And can you successfully call the system `presentTextInputControllerWithSuggestions` method, the one without the `flickTypeMode` argument?

**Comment by ramz3001** [comment]
yes sure it is,

here it is in .h file.

#import <WatchKit/WatchKit.h>
#import <Foundation/Foundation.h>

@interface TableViewRowController : WKInterfaceController

On Jun 7, 2019, at 12:22 AM, Kosta Eleftheriou <notifications@github.com<mailto:notifications@github.com>> wrote:


You can only call presentTextInputControllerWithSuggestions on a WKInterfaceController.

Is your TableViewRowController a subclass of WKInterfaceController?

And can you successfully call the system presentTextInputControllerWithSuggestions method, the one without the flickTypeMode argument?

**Comment by keleftheriou** [comment]
I'm not sure as I have not done this myself. But I believe @afrazsiddiqui has integrated it in an Objective-C project and may be able to help?

**Comment by ramz3001** [comment]
Ok thanks bro , i wanted to ask you , i doubd that you hoooked the methods as swift , if i hooked thme as objective c do you think it would work ?

Sent from my iPhone

On Jun 7, 2019, at 1:50 AM, Kosta Eleftheriou <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure as I have not done this myself. But I believe @afrazsiddiqui<https://github.com/afrazsiddiqui> has integrated it in an Objective-C project and may be able to help?

**Comment by AfrazCodes** [comment]
@keleftheriou @ramz3001 super late to this party but I have had it working with Obj-C for many months. In process of upgrading versions now actually. PS: I think you mentioned the wrong person above haha. Are you still facing this issue?

**Comment by keleftheriou** [comment]
Thank you @AfrazCodes. Please make sure you use the updated screenshots for this version which you can find here: https://github.com/FlickType/FlickTypeKit/blob/master/LICENSE.md
Thanks!

**Comment by AfrazCodes** [comment]
You got it! @keleftheriou fyi, got the updated version working as well.

**Comment by ramz3001** [comment]
Hello ,

@afrazcodes thank you for your reply , i did a workaround and it did work , but i did not like much this solution so i did not add it yet, if you have a solution that you can share, i would appreciate it a lot. Thanks in advance

Sent from my iPhone

On Jul 7, 2019, at 4:31 AM, Afraz Siddiqui <notifications@github.com<mailto:notifications@github.com>> wrote:


@keleftheriou<https://github.com/keleftheriou> @ramz3001<https://github.com/ramz3001> super late to this party but I have had it working with Obj-C for many months. In process of upgrading versions now actually. PS: I think you mentioned the wrong person above haha. Are you still facing this issue?

**Comment by AfrazCodes** [comment]
@ramz3001 Because you, a few of my colleagues, and others around the Internet have asked how to set this up in Obj-C, I've created this little walkthrough video on my new iOS Youtube channel. Hope it helps: https://www.youtube.com/watch?v=f7TkCE7gaDc&feature=youtu.be

**Comment by keleftheriou** [comment]
Thank you @AfrazCodes. Closing the issue now.

**Comment by ramz3001** [comment]
Thanks bro i really appreciate it

Sent from my iPhone

On Jul 7, 2019, at 11:36 PM, Afraz Siddiqui <notifications@github.com<mailto:notifications@github.com>> wrote:


@ramz3001<https://github.com/ramz3001> Because you, a few of my colleagues, and others around the Internet have asked how to set this up in Obj-C, I've created this little walkthrough video on my new iOS Youtube channel. Hope it helps: https://www.youtube.com/watch?v=f7TkCE7gaDc&feature=youtu.be

**Comment by AfrazCodes** [comment]
@keleftheriou @ramz3001 glad I could help.
