### ISSUE TITLE
FlickType from master and swift-5.1 branches are incompatible with Xcode 11

### ISSUE THREAD

**Issue by wernjie** [FlickType/FlickTypeKit#2]
It appears that the framework in the master branch is not compiled for swift 5.1, and that the swift-5.1 branch is not updated to be compiled with the official release of Xcode 11, thus couldn't be included as Xcode 11 requests rebuilding the framework.

In Xcode 11, the message "Compiled module was created by an older version of the compiler; rebuild FlickTypeKit and try again" is shown.

Thanks.

**Comment by keleftheriou** [comment]
Please checkout the new `xcframework` branch which should resolve this issue, as well as make things future-proof.

**Comment by wernjie** [comment]
Thanks a lot, the one in the new `xcframework` branch worked flawlessly for me.
